// <auto-generated />
namespace EApartments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_status_col_on_apartments_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_status_col_on_apartments_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202301181203126_change_status_col_on_apartments_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
