// <auto-generated />
namespace EApartments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_lease_table_requested_to_col : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_lease_table_requested_to_col));
        
        string IMigrationMetadata.Id
        {
            get { return "202301220043150_update_lease_table_requested_to_col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
